SET FOREIGN_KEY_CHECKS=0;

DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM cart_items;
DELETE FROM shopping_carts;
DELETE FROM books_categories;
DELETE FROM books;
DELETE FROM users;
DELETE FROM categories;

ALTER TABLE categories AUTO_INCREMENT = 1;
ALTER TABLE books AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE orders AUTO_INCREMENT = 1;
ALTER TABLE shopping_carts AUTO_INCREMENT = 1;
ALTER TABLE order_items AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS=1;
